#!/bin/bash

if [ "$1" == "" ]; then
	if [ -f ".runtests.txt" ]; then
		TESTS=`cat .runtests.txt`
	fi
elif [ "$1" == "-" ]; then
	rm -f .runtests.txt
else
	TESTS="$1"
	echo "$TESTS" >.runtests.txt
fi
python3 -c 'import toyecc.tests'
if [ "$?" != "0" ]; then
	exit 1
fi
if [ "$TESTS" == "" ]; then
	python3 -m unittest toyecc.tests ${TESTS}
else
	python3 -m unittest "toyecc.tests.${TESTS}"
fi
